### ISSUE TITLE
remove all references to staticman endpoints that are affected by quotas

### ISSUE THREAD

**Issue by onweru** [onweru/hugo-swift-theme#47]
It is now obvious that [the public instance of staticman is broken](https://github.com/eduardoboucas/staticman/issues/307#issuecomment-515362228), and will probably stay that way indefinitely. 

It would then make sense to remove any reference to that endpoint. Why? It's misleading as an option, since it doesn't work anyway.  This is also true for all links that point to the dated [staticman docs](https://staticman.net/docs/). It doesn't matter if some sections of those docs work if as a whole, they don't get the job done.

As a courtesy to users, **it would be  immensely helpful to  only document options that actually work**. Is it possible to document a concise guide so that one doesn't have to get lost in the weeds (issue threads and fractured documentation pages)? .

What we have at the moment reads like `this is the default option but it doesn't work, but you can try it`. 

In hind sight, this  👇 too needs to be removed. Why? At this point, these information is another turn deeper into the annoying rabbit 🐇 hole.

> :information_source: This [Binary Mist article](https://binarymist.io/blog/2018/02/24/hugo-with-staticman-commenting-and-subscriptions/) could also be quite helpful :)
:information_source: By default, this theme uses the official production instance at v3 instead of v2 due to a requests' quota issue reported in issue [eduardoboucas/staticman#222](https://github.com/eduardoboucas/staticman/issues/222).
:warning: Since Staticman is an evolving project, things might work differently than they do at the moment of this writing.

We need to rethink the [staticman section](https://github.com/onweru/hugo-swift-theme#staticman-comments) because as it is, it utterly frustrating to anyone looking to get up and running quickly.

Maybe we could even extract it to a dedicated documentation page(s), with procedures that work. All other references could then be linked as footnotes.

**Comment by VincentTam** [comment]
Move detailed instructions like the following to the Wiki page, and keep the essential parts.

* * *

# :construction_worker_man: Staticman Configurations for Beautiful Jekyll

:email: Please don't hesitate to ping me on GitHub/GitLab/leave a comment on my blog/send me an email to ask for help.

1. :checkered_flag: Invite @staticmanlab as a collaborator to your repository (by going to your repository Settings page, navigate to the Collaborators tab).  
![send invitation to Staticman Lab](https://git.io/fjZPx)  
Image short link: https://git.io/fjZPx
2. :ballot_box_with_check: Help @staticmanlab accept the invitation by going to

        https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>

    In your case, that's

        https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>

    ![Staticman Lab invitation accepted](https://camo.githubusercontent.com/fca08dcc33537c78f0b56e934afde4af0605f706/68747470733a2f2f76696e63656e7474616d2e6769746c61622e696f2f706f73742f323031382d31322d31392d7374617469636d616e2d696e7669746174696f6e2d69732d636173652d73656e7369746976652f696e76697465322e706e67)  
    Figure: image showing setup for [my fork of this theme](//git.io/bjsm0)  
    Image short link: https://git.io/fjZXG

    ![Staticman Lab shown as collaborator](https://camo.githubusercontent.com/eb3d86ecf35497912c485fb2d339d9d3cd962197/68747470733a2f2f76696e63656e7474616d2e6769746c61622e696f2f706f73742f323031382d31322d31392d7374617469636d616e2d696e7669746174696f6e2d69732d636173652d73656e7369746976652f696e76697465332e706e67)  
    Figure: @staticmanlab invited to GitHub repo  
    Image short link: https://git.io/fjZXZ

3. :writing_hand: Fill in your `repository` and `branch` in the Staticman section of `_config.yml`.

    ```yml
     # Staticman support 
     staticman: 
       repository : "<username>/<repo-name>" # GitHub username/repository eg. "daattali/beautiful-jekyll" 
       branch     : "master" # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml` 
       endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance) 
       reCaptcha: 
         # reCaptcha for Staticman (OPTIONAL) 
         # If you use reCaptcha, you must also set these parameters in staticman.yml 
         siteKey  : # Use your own site key, you need to apply for one on Google 
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret> 
    ```

4. :memo: Start commenting.
